//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriviaGame.MessageLibrary", typeof(MessageLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █▀▀ █▀█ █▀█ █▀█ █▀▀ █▀▀ ▀█▀
        ///█▄▄ █▄█ █▀▄ █▀▄ ██▄ █▄▄ ░█░.
        /// </summary>
        internal static string correct {
            get {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░▒▒▒▒░░░▒▒▒▒░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒░▒▒▒▒▒▒░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒░░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒░░░░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░▒░░░░░░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒░▒▒▒░░░▓▓
        ///▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .-----.-------------------------------.
        ///|Press|       Action                  |
        ///|-----|-------------------------------|
        ///|  1  |    Start the game             |
        ///|  2  |    Enter number of questions  |
        ///|  3  |    End the game               |
        ///&apos;-----&apos;------------------------------&apos;&quot;.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULES
        ///* Players must correctly answer questions in the seelected category.
        ///* To win, a player must correctly answers a certain number of questions.
        ///
        ///GAMEPLAY
        ///* The player starts the game from the main menu.
        ///* The player can enter the number of trivia questions. (NOTE: must be 1 or greater)
        ///* The game randomly presents a multiple choice question.
        ///* The player enters their selection.
        ///* If the player answers correctly they receive X point(s).
        ///* If the player answers incorrectly the game advances to t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ████████╗███████╗░█████╗░██╗░░██╗  ████████╗██████╗░██╗██╗░░░██╗░█████╗░
        ///╚══██╔══╝██╔════╝██╔══██╗██║░░██║  ╚══██╔══╝██╔══██╗██║██║░░░██║██╔══██╗
        ///░░░██║░░░█████╗░░██║░░╚═╝███████║  ░░░██║░░░██████╔╝██║╚██╗░██╔╝███████║
        ///░░░██║░░░██╔══╝░░██║░░██╗██╔══██║  ░░░██║░░░██╔══██╗██║░╚████╔╝░██╔══██║
        ///░░░██║░░░███████╗╚█████╔╝██║░░██║  ░░░██║░░░██║░░██║██║░░╚██╔╝░░██║░░██║
        ///░░░╚═╝░░░╚══════╝░╚════╝░╚═╝░░╚═╝  ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░░╚═╝░░░╚═╝░░╚═╝.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ██╗░░░██╗░█████╗░██╗░░░██╗  ░██╗░░░░░░░██╗██╗███╗░░██╗██╗
        ///╚██╗░██╔╝██╔══██╗██║░░░██║  ░██║░░██╗░░██║██║████╗░██║██║
        ///░╚████╔╝░██║░░██║██║░░░██║  ░╚██╗████╗██╔╝██║██╔██╗██║██║
        ///░░╚██╔╝░░██║░░██║██║░░░██║  ░░████╔═████║░██║██║╚████║╚═╝
        ///░░░██║░░░╚█████╔╝╚██████╔╝  ░░╚██╔╝░╚██╔╝░██║██║░╚███║██╗
        ///░░░╚═╝░░░░╚════╝░░╚═════╝░  ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═╝.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █░█░█ █▀█ █▀█ █▄░█ █▀▀
        ///▀▄▀▄▀ █▀▄ █▄█ █░▀█ █▄█.
        /// </summary>
        internal static string wrong {
            get {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
    }
}
